package com.mtr.model;

public class MeetingRoom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.ID
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.NAME
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.DESK
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    private Boolean desk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.MEDIA
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    private Boolean media;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.AIRCONDITION
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    private Boolean aircondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.PEOPLE
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    private Integer people;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.MICROPHONE
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    private Integer microphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.WHITEBOARD
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    private Integer whiteboard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.BLACKBOARD
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    private Integer blackboard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.ID
     *
     * @return the value of meeting_room.ID
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.ID
     *
     * @param id the value for meeting_room.ID
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.NAME
     *
     * @return the value of meeting_room.NAME
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.NAME
     *
     * @param name the value for meeting_room.NAME
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.DESK
     *
     * @return the value of meeting_room.DESK
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public Boolean getDesk() {
        return desk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.DESK
     *
     * @param desk the value for meeting_room.DESK
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public void setDesk(Boolean desk) {
        this.desk = desk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.MEDIA
     *
     * @return the value of meeting_room.MEDIA
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public Boolean getMedia() {
        return media;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.MEDIA
     *
     * @param media the value for meeting_room.MEDIA
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public void setMedia(Boolean media) {
        this.media = media;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.AIRCONDITION
     *
     * @return the value of meeting_room.AIRCONDITION
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public Boolean getAircondition() {
        return aircondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.AIRCONDITION
     *
     * @param aircondition the value for meeting_room.AIRCONDITION
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public void setAircondition(Boolean aircondition) {
        this.aircondition = aircondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.PEOPLE
     *
     * @return the value of meeting_room.PEOPLE
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.PEOPLE
     *
     * @param people the value for meeting_room.PEOPLE
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.MICROPHONE
     *
     * @return the value of meeting_room.MICROPHONE
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public Integer getMicrophone() {
        return microphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.MICROPHONE
     *
     * @param microphone the value for meeting_room.MICROPHONE
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public void setMicrophone(Integer microphone) {
        this.microphone = microphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.WHITEBOARD
     *
     * @return the value of meeting_room.WHITEBOARD
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public Integer getWhiteboard() {
        return whiteboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.WHITEBOARD
     *
     * @param whiteboard the value for meeting_room.WHITEBOARD
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public void setWhiteboard(Integer whiteboard) {
        this.whiteboard = whiteboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.BLACKBOARD
     *
     * @return the value of meeting_room.BLACKBOARD
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public Integer getBlackboard() {
        return blackboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.BLACKBOARD
     *
     * @param blackboard the value for meeting_room.BLACKBOARD
     *
     * @mbg.generated Mon Dec 12 17:21:01 CST 2016
     */
    public void setBlackboard(Integer blackboard) {
        this.blackboard = blackboard;
    }
}