package com.mtr.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ID
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.START_TIME
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.END_TIME
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.BOOKED_BY
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    private Integer bookedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.MEETING_ROOM
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    private Integer meetingRoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.THEME
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.REMARK
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.TYPE
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.CONTRACTER
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    private Integer contracter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ID
     *
     * @return the value of order.ID
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ID
     *
     * @param id the value for order.ID
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.START_TIME
     *
     * @return the value of order.START_TIME
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.START_TIME
     *
     * @param startTime the value for order.START_TIME
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.END_TIME
     *
     * @return the value of order.END_TIME
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.END_TIME
     *
     * @param endTime the value for order.END_TIME
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.BOOKED_BY
     *
     * @return the value of order.BOOKED_BY
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public Integer getBookedBy() {
        return bookedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.BOOKED_BY
     *
     * @param bookedBy the value for order.BOOKED_BY
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public void setBookedBy(Integer bookedBy) {
        this.bookedBy = bookedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.MEETING_ROOM
     *
     * @return the value of order.MEETING_ROOM
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public Integer getMeetingRoom() {
        return meetingRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.MEETING_ROOM
     *
     * @param meetingRoom the value for order.MEETING_ROOM
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public void setMeetingRoom(Integer meetingRoom) {
        this.meetingRoom = meetingRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.THEME
     *
     * @return the value of order.THEME
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.THEME
     *
     * @param theme the value for order.THEME
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.REMARK
     *
     * @return the value of order.REMARK
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.REMARK
     *
     * @param remark the value for order.REMARK
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.TYPE
     *
     * @return the value of order.TYPE
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.TYPE
     *
     * @param type the value for order.TYPE
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.CONTRACTER
     *
     * @return the value of order.CONTRACTER
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public Integer getContracter() {
        return contracter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.CONTRACTER
     *
     * @param contracter the value for order.CONTRACTER
     *
     * @mbg.generated Tue Nov 22 00:34:44 CST 2016
     */
    public void setContracter(Integer contracter) {
        this.contracter = contracter;
    }
}